from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
import bcrypt

db = SQLAlchemy()

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(128), nullable=False)
    is_admin = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

class Prediction(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    age = db.Column(db.Float)
    gender = db.Column(db.Integer)
    bmi = db.Column(db.Float)
    hemoglobin = db.Column(db.Float)
    wbc = db.Column(db.Float)
    rbc = db.Column(db.Float)
    platelets = db.Column(db.Float)
    glucose_fasting = db.Column(db.Float)
    hba1c = db.Column(db.Float)
    cholesterol_total = db.Column(db.Float)
    triglycerides = db.Column(db.Float)
    ldl = db.Column(db.Float)
    hdl = db.Column(db.Float)
    alt = db.Column(db.Float)
    ast = db.Column(db.Float)
    bilirubin_total = db.Column(db.Float)
    creatinine = db.Column(db.Float)
    urea = db.Column(db.Float)
    tsh = db.Column(db.Float)
    t3 = db.Column(db.Float)
    t4 = db.Column(db.Float)
    crp = db.Column(db.Float)
    smoker = db.Column(db.Integer)
    alcohol_intake = db.Column(db.Integer)
    covid_antigen_pos = db.Column(db.Integer)
    hiv_positive = db.Column(db.Integer)
    hepatitis_b_pos = db.Column(db.Integer)
    hepatitis_c_pos = db.Column(db.Integer)
    malaria_positive = db.Column(db.Integer)
    tuberculosis_pos = db.Column(db.Integer)
    exercise_freq = db.Column(db.String(50))
    predicted_disease = db.Column(db.String(100))
    confidence = db.Column(db.Float)
    prediction_date = db.Column(db.DateTime, default=datetime.utcnow)